name: flutter8
description: Flutter8 platform implementation.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  syntax_highlight: ^0.2.0
  visibility_detector: any
  go_router: ^12.1.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.0
  either_dart: ^1.0.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  firebase_app_check: ^0.2.0+1
  cloud_firestore: ^4.9.3
  copy_with_extension: ^5.0.4
  json_annotation: ^4.8.0
  confetti: ^0.7.0
  queue: ^3.1.0+2
  flutter_svg: ^2.0.7
  sa3_liquid: ^1.0.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  copy_with_extension_gen: ^5.0.4
  build_runner: ^2.1.7
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - env/default.env
    - assets/logo.svg
